# Generated by Django 3.1.2 on 2021-02-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabExam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('exam_date', models.DateField(auto_now_add=True)),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_description', models.TextField(max_length=200)),
                ('total_marks', models.FloatField()),
                ('pass_mark', models.FloatField()),
                ('exam_status', models.BooleanField(default=True)),
            ],
        ),
    ]
